---

- name: IPv6 Globally Enable
  hosts: R1 
  gather_facts: false
  connection: local

  vars: 
    cli:
      username: berenger
      password: passer
      timeout: 60
  
  tasks:
    - name: Global config setting 
      ios_config:
        provider: "{{ cli }}"
        lines:
         - ipv6 unicast-routing

      register: print_output

