---

- hosts: hosts
  tasks:
    - name: installation freeradius
      apt:
         name: freeradius
         update_cache: yes
         cache_valid_time: 3600
         state: present
            

        







        







